import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";

import type { Metadata } from "next";
import Script from "next/script";

import { Nav } from "@/components/nav/nav";
import { NowPlayingProvider } from "@/components/now-playing-provider";
import { Player } from "@/components/player";

import { MixcloudPlayer } from "./mixcloud-player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className="font-chivo">
        <Nav />
        <NowPlayingProvider>
          <Player />
          {children}
          <MixcloudPlayer />
        </NowPlayingProvider>
      </body>
      <Script src="//widget.mixcloud.com/media/js/widgetApi.js" />
    </html>
  );
}
