import type { Metadata } from "next";

import { fetchShows } from "@/api";
import { NowPlayingProvider } from "@/components/now-playing-provider";
import { Nav } from "@/components/nav/nav";
import { Player } from "@/components/player";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const shows = await fetchShows();
  return (
    <html lang="en">
      <head></head>
      <body>
        <Nav />
        <NowPlayingProvider initCurrentShow={shows.current}>
          <Player />
          {children}
        </NowPlayingProvider>
      </body>
    </html>
  );
}
